/**
 * 吉卜力AI转换工具语言包
 * 支持中文和英文切换
 */

// 语言数据包
const languageData = {
    // 导航菜单
    'nav.home': {
        'zh': '首页',
        'en': 'Home'
    },
    'nav.generator': {
        'zh': '生成工具',
        'en': 'Generator'
    },
    'nav.gallery': {
        'zh': '作品展示',
        'en': 'Gallery'
    },
    'nav.about': {
        'zh': '关于我们',
        'en': 'About Us'
    },
    
    // 首页主横幅
    'home.banner.title': {
        'zh': '将你的照片变成吉卜力动画风格',
        'en': 'Transform Your Photos into Ghibli Animation Style'
    },
    'home.banner.subtitle': {
        'zh': '使用我们的AI技术，创造属于你的宫崎骏世界',
        'en': 'Create your own Miyazaki world with our AI technology'
    },
    'home.banner.start': {
        'zh': '开始创作',
        'en': 'Start Creating'
    },
    'home.banner.view': {
        'zh': '查看作品',
        'en': 'View Works'
    },
    
    // 生成器区域
    'generator.title': {
        'zh': '创建你的吉卜力风格作品',
        'en': 'Create Your Ghibli Style Artwork'
    },
    'generator.subtitle': {
        'zh': '上传照片，几分钟内将作品发送到您的邮箱',
        'en': 'Upload a photo and receive your artwork in your mailbox within minutes'
    },
    'generator.email': {
        'zh': '电子邮箱地址',
        'en': 'Email Address'
    },
    'generator.upload': {
        'zh': '上传照片',
        'en': 'Upload Photo'
    },
    'generator.upload.hint': {
        'zh': '点击或拖放照片到这里',
        'en': 'Click or Drop Photos Here'
    },
    'generator.upload.formats': {
        'zh': '支持JPG、PNG格式，最大5MB',
        'en': 'JPG, PNG formats, max 5MB'
    },
    'generator.remove': {
        'zh': '移除图片',
        'en': 'Remove Image'
    },
    'generator.submit': {
        'zh': '生成吉卜力风格作品',
        'en': 'Generate Ghibli Style Artwork'
    },
    'generator.processing': {
        'zh': '处理中...',
        'en': 'Processing...'
    },
    'generator.success': {
        'zh': '您的请求已成功提交！我们将在处理完成后发送结果到您的邮箱，请注意查收。',
        'en': 'Your request has been successfully submitted! We will send the result to your email after processing. Please check your inbox.'
    },
    
    // 特色功能区域
    'features.title': {
        'zh': '为什么选择我们的AI生成器',
        'en': 'Why Choose Our AI Generator'
    },
    'features.subtitle': {
        'zh': '无需专业技能，轻松创造吉卜力风格的艺术作品',
        'en': 'Easily create Ghibli-style artwork without professional skills'
    },
    
    // 特色功能项
    'feature.ai.title': {
        'zh': '先进AI技术',
        'en': 'Advanced AI Technology'
    },
    'feature.ai.desc': {
        'zh': '采用最先进的人工智能和深度学习技术，精确捕捉吉卜力作品的艺术特点，确保高品质的转换效果。',
        'en': 'Using the most advanced AI and deep learning technology to accurately capture the artistic features of Ghibli works, ensuring high-quality conversion effects.'
    },
    
    'feature.styles.title': {
        'zh': '多种风格选择',
        'en': 'Multiple Style Options'
    },
    'feature.styles.desc': {
        'zh': '提供《龙猫》、《千与千寻》、《哈尔的移动城堡》等多种经典吉卜力电影风格，满足不同创作需求。',
        'en': 'Offering multiple classic Ghibli movie styles like Totoro, Spirited Away, Howl\'s Moving Castle, meeting different creative needs.'
    },
    
    'feature.speed.title': {
        'zh': '超快处理速度',
        'en': 'Ultra-fast Processing'
    },
    'feature.speed.desc': {
        'zh': '优化的图像处理流程，让你只需短短几秒即可获得高质量的吉卜力风格作品，无需漫长等待。',
        'en': 'Optimized image processing allows you to get high-quality Ghibli-style works in just a few seconds, without long waits.'
    },
    
    // 示例展示区域
    'examples.title': {
        'zh': '吉卜力风格示例',
        'en': 'Ghibli Style Examples'
    },
    'examples.subtitle': {
        'zh': '看看我们的AI如何将普通照片转换成宫崎骏风格的艺术作品',
        'en': 'See how our AI transforms ordinary photos into Miyazaki-style artwork'
    },
    'examples.more': {
        'zh': '查看更多示例',
        'en': 'See More Examples'
    },
    
    // 作品展示页
    'gallery.title': {
        'zh': '吉卜力风格作品展示',
        'en': 'Ghibli Style Gallery'
    },
    'gallery.subtitle': {
        'zh': '欣赏由AI生成的宫崎骏风格艺术作品',
        'en': 'Enjoy Miyazaki-style artwork generated by AI'
    },
    'gallery.all': {
        'zh': '全部作品',
        'en': 'All Works'
    },
    'gallery.totoro': {
        'zh': '龙猫风格',
        'en': 'Totoro Style'
    },
    'gallery.spirited': {
        'zh': '千与千寻风格',
        'en': 'Spirited Away Style'
    },
    'gallery.howl': {
        'zh': '哈尔的移动城堡风格',
        'en': 'Howl\'s Moving Castle Style'
    },
    'gallery.other': {
        'zh': '其他风格',
        'en': 'Other Styles'
    },
    
    // 页脚区域
    'footer.description': {
        'zh': '使用AI技术创造宫崎骏风格的艺术作品，让每个人都能成为吉卜力艺术家。',
        'en': 'Create Miyazaki-style artwork using AI technology, allowing everyone to become a Ghibli artist.'
    },
    'footer.quicklinks': {
        'zh': '快速链接',
        'en': 'Quick Links'
    },
    'footer.contact': {
        'zh': '联系我们',
        'en': 'Contact Us'
    },
    'footer.copyright': {
        'zh': '保留所有权利。',
        'en': 'All Rights Reserved.'
    },
    'footer.disclaimer': {
        'zh': '本站与吉卜力工作室没有任何关联。吉卜力风格仅指视觉艺术风格。',
        'en': 'This site has no affiliation with Studio Ghibli. Ghibli style refers only to the visual art style.'
    },
    
    // 特色功能项 - 新增条目
    'feature.dual.title': {
        'zh': '双重创作模式',
        'en': 'Dual Creation Mode'
    },
    'feature.dual.desc': {
        'zh': '支持图片转换和文字生成两种模式，无论是转换现有照片还是从文字描述创造全新画面，都能轻松实现。',
        'en': 'Supporting both image conversion and text generation modes, whether converting existing photos or creating new images from text descriptions.'
    },
    'feature.download.title': {
        'zh': '高清下载分享',
        'en': 'HD Download & Share'
    },
    'feature.download.desc': {
        'zh': '生成的作品支持高分辨率下载，适合打印或在社交媒体上分享，让更多人欣赏你的吉卜力风格创作。',
        'en': 'Generated works support high-resolution downloads, suitable for printing or sharing on social media.'
    },
    'feature.love.title': {
        'zh': '热爱与尊重',
        'en': 'Love & Respect'
    },
    'feature.love.desc': {
        'zh': '由热爱宫崎骏和吉卜力作品的团队开发，我们深刻理解并尊重这些作品的艺术价值和美学特点。',
        'en': 'Developed by a team that loves Miyazaki and Ghibli works, we deeply understand and respect the artistic value and aesthetic features of these works.'
    },
    
    // 示例卡片内容
    'examples.totoro.title': {
        'zh': '龙猫风格',
        'en': 'Totoro Style'
    },
    'examples.totoro.desc': {
        'zh': '充满自然和温馨的田园风光',
        'en': 'Pastoral scenery full of nature and warmth'
    },
    'examples.totoro.alt': {
        'zh': '龙猫风格示例',
        'en': 'Totoro Style Example'
    },
    'examples.spirited.title': {
        'zh': '千与千寻风格',
        'en': 'Spirited Away Style'
    },
    'examples.spirited.desc': {
        'zh': '神秘奇幻的幽灵世界',
        'en': 'Mysterious and fantastical spirit world'
    },
    'examples.spirited.alt': {
        'zh': '千与千寻风格示例',
        'en': 'Spirited Away Style Example'
    },
    'examples.howl.title': {
        'zh': '哈尔的移动城堡风格',
        'en': 'Howl\'s Moving Castle Style'
    },
    'examples.howl.desc': {
        'zh': '蒸汽朋克与魔法的融合',
        'en': 'Fusion of steampunk and magic'
    },
    'examples.howl.alt': {
        'zh': '哈尔的移动城堡风格示例',
        'en': 'Howl\'s Moving Castle Style Example'
    },
    
    // 吉卜力风格特点
    'style.title': {
        'zh': '吉卜力风格的独特魅力',
        'en': 'The Unique Charm of Ghibli Style'
    },
    'style.subtitle': {
        'zh': '我们的AI能够准确捕捉这些艺术特点',
        'en': 'Our AI can accurately capture these artistic features'
    },
    'style.nature.title': {
        'zh': '精美自然景观',
        'en': 'Exquisite Natural Landscapes'
    },
    'style.nature.desc': {
        'zh': '宫崎骏作品中的自然环境描绘极为精细，无论是茂密的森林、广阔的草原还是宁静的湖泊，都充满了生命力和细节。我们的AI能够将这种对自然的细腻表现应用到你的照片中。',
        'en': 'The natural environments in Miyazaki\'s works are depicted in great detail, whether dense forests, vast grasslands or serene lakes, all full of vitality and detail. Our AI can apply this delicate representation of nature to your photos.'
    },
    'style.light.title': {
        'zh': '梦幻光影效果',
        'en': 'Dreamy Light Effects'
    },
    'style.light.desc': {
        'zh': '吉卜力作品中的光线处理独具特色，柔和的阳光、神秘的月光或魔法的光芒，都为画面增添了独特的氛围。我们的AI能够重现这种梦幻般的光影效果。',
        'en': 'The light treatment in Ghibli works is distinctive, with soft sunlight, mysterious moonlight or magical radiance all adding unique atmosphere to the scene. Our AI can recreate these dreamy light effects.'
    },
    'style.texture.title': {
        'zh': '水彩般的质感',
        'en': 'Watercolor-like Texture'
    },
    'style.texture.desc': {
        'zh': '吉卜力作品常采用传统手绘动画技术，呈现出水彩画般的柔和质感。我们的AI能够模拟这种独特的绘画风格，赋予照片温暖而艺术的质感。',
        'en': 'Ghibli works often use traditional hand-drawn animation techniques, presenting a soft watercolor-like texture. Our AI can simulate this unique painting style, giving photos a warm and artistic texture.'
    },
    'style.fantasy.title': {
        'zh': '奇幻与现实的融合',
        'en': 'Fusion of Fantasy and Reality'
    },
    'style.fantasy.desc': {
        'zh': '宫崎骏的作品常将奇幻元素与现实世界巧妙融合，创造出既熟悉又陌生的世界。我们的AI能够在保留照片原有元素的同时，添加这种独特的奇幻感。',
        'en': 'Miyazaki\'s works often cleverly blend fantasy elements with the real world, creating worlds that are both familiar and strange. Our AI can add this unique sense of fantasy while preserving the original elements of the photo.'
    },
    
    // 用户评价
    'testimonials.title': {
        'zh': '用户评价',
        'en': 'User Reviews'
    },
    'testimonials.subtitle': {
        'zh': '看看其他用户如何评价我们的AI生成器',
        'en': 'See what other users say about our AI generator'
    },
    'testimonials.user1.content': {
        'zh': '这个工具太神奇了！我把自家院子的照片转换成了龙猫风格，效果惊人。现在这张照片已经成为我客厅里的装饰画，每个来访的朋友都赞不绝口。',
        'en': 'This tool is amazing! I converted a photo of my backyard into Totoro style, and the result is incredible. Now this photo has become a decorative painting in my living room, and every visiting friend compliments it.'
    },
    'testimonials.user1.name': {
        'zh': '李小明',
        'en': 'David Chen'
    },
    'testimonials.user1.role': {
        'zh': '摄影爱好者',
        'en': 'Photography Enthusiast'
    },
    'testimonials.user2.content': {
        'zh': '作为一名小学美术老师，我经常使用这个工具来激发学生的创造力。孩子们看到自己的画作变成吉卜力风格后都非常兴奋，这增强了他们对艺术的兴趣。',
        'en': 'As an elementary school art teacher, I often use this tool to inspire students\' creativity. The children are very excited to see their drawings transformed into Ghibli style, which enhances their interest in art.'
    },
    'testimonials.user2.name': {
        'zh': '张老师',
        'en': 'Ms. Johnson'
    },
    'testimonials.user2.role': {
        'zh': '小学美术教师',
        'en': 'Elementary Art Teacher'
    },
    'testimonials.user3.content': {
        'zh': '我是宫崎骏作品的忠实粉丝，这个AI生成器完美捕捉了吉卜力的艺术风格。我用它为自己写的小说创作了插图，现在我的读者们都在追问我是从哪里找到这么棒的插画师的。',
        'en': 'I\'m a devoted fan of Miyazaki\'s works, and this AI generator perfectly captures the artistic style of Ghibli. I used it to create illustrations for my novel, and now my readers are all asking where I found such a great illustrator.'
    },
    'testimonials.user3.name': {
        'zh': '王佳佳',
        'en': 'Sarah Miller'
    },
    'testimonials.user3.role': {
        'zh': '网络小说作者',
        'en': 'Online Novelist'
    },
    
    // 常见问题
    'faq.title': {
        'zh': '常见问题',
        'en': 'FAQ'
    },
    'faq.subtitle': {
        'zh': '关于我们AI生成器的一些常见疑问',
        'en': 'Common questions about our AI generator'
    },
    'faq.q1.title': {
        'zh': '我需要有绘画或设计技能吗？',
        'en': 'Do I need drawing or design skills?'
    },
    'faq.q1.answer': {
        'zh': '完全不需要。我们的AI生成器设计得非常直观易用，即使没有任何绘画或设计经验的用户也能轻松创造出精美的吉卜力风格作品。你只需上传照片或输入描述，选择风格，剩下的交给AI来完成。',
        'en': 'Not at all. Our AI generator is designed to be very intuitive and easy to use, allowing users without any drawing or design experience to easily create beautiful Ghibli-style works. You just need to upload a photo or enter a description, choose a style, and leave the rest to the AI.'
    },
    'faq.q2.title': {
        'zh': '转换后的图像质量如何？',
        'en': 'How is the quality of converted images?'
    },
    'faq.q2.answer': {
        'zh': '我们的AI生成器能够输出高分辨率图像，适合在社交媒体分享、打印或作为艺术品展示。图像质量取决于上传照片的原始质量，但我们的AI会尽可能保留细节同时应用吉卜力艺术风格。',
        'en': 'Our AI generator can output high-resolution images suitable for sharing on social media, printing, or displaying as artwork. Image quality depends on the original quality of the uploaded photo, but our AI will preserve details as much as possible while applying the Ghibli artistic style.'
    },
    'faq.q3.title': {
        'zh': '可以用于商业目的吗？',
        'en': 'Can it be used for commercial purposes?'
    },
    'faq.q3.answer': {
        'zh': '生成的作品可用于个人用途，包括社交媒体分享和个人创作。如需用于商业目的，请查阅我们的服务条款或联系我们获取商业授权。请注意，吉卜力工作室的原创风格存在版权保护。',
        'en': 'Generated works can be used for personal purposes, including social media sharing and personal creation. For commercial use, please refer to our terms of service or contact us for commercial authorization. Please note that Studio Ghibli\'s original style is protected by copyright.'
    },
    'faq.q4.title': {
        'zh': '我的照片和生成的作品安全吗？',
        'en': 'Are my photos and generated works safe?'
    },
    'faq.q4.answer': {
        'zh': '我们非常重视用户隐私。上传的照片和生成的作品不会被永久保存在我们的服务器上，处理完成后将自动删除。我们不会将你的照片或作品用于任何未经授权的用途。',
        'en': 'We take user privacy very seriously. Uploaded photos and generated works will not be permanently stored on our servers and will be automatically deleted after processing. We will not use your photos or works for any unauthorized purposes.'
    },
    'faq.more': {
        'zh': '查看更多问题',
        'en': 'View More Questions'
    },
    
    // 行动召唤
    'cta.title': {
        'zh': '准备好创造你的吉卜力风格作品了吗？',
        'en': 'Ready to Create Your Ghibli Style Artwork?'
    },
    'cta.subtitle': {
        'zh': '立即体验我们的AI生成器，将你的照片或想法变成宫崎骏风格的艺术品',
        'en': 'Experience our AI generator now and turn your photos or ideas into Miyazaki-style artwork'
    },
    'cta.button': {
        'zh': '开始创作',
        'en': 'Start Creating'
    },
    
    // 页脚链接
    'footer.privacy': {
        'zh': '隐私政策',
        'en': 'Privacy Policy'
    },
    'footer.terms': {
        'zh': '服务条款',
        'en': 'Terms of Service'
    },
    'footer.email': {
        'zh': 'contact@ghibliai.com',
        'en': 'contact@ghibliai.com'
    },
    'footer.phone': {
        'zh': '+86 123 4567 8900',
        'en': '+1 (800) 123-4567'
    },
    'footer.address': {
        'zh': '北京市朝阳区创意园区A座',
        'en': 'Creative Park Building A, San Francisco, CA'
    }
};

// 语言切换函数
function toggleLanguage(lang) {
    // 更新所有带有data-lang-key属性的元素
    $('[data-lang-key]').each(function() {
        const key = $(this).data('lang-key');
        if (languageData[key] && languageData[key][lang]) {
            $(this).html(languageData[key][lang]);
        }
    });
    
    // 更新placeholder
    $('[data-lang-placeholder]').each(function() {
        const key = $(this).data('lang-placeholder');
        if (languageData[key] && languageData[key][lang]) {
            $(this).attr('placeholder', languageData[key][lang]);
        }
    });
    
    // 特殊处理alt文本
    $('[data-lang-alt]').each(function() {
        const key = $(this).data('lang-alt');
        if (languageData[key] && languageData[key][lang]) {
            $(this).attr('alt', languageData[key][lang]);
        }
    });
    
    // 设置文档语言
    $('html').attr('lang', lang);
    
    // 触发自定义事件，以便其他脚本可以响应语言更改
    $(document).trigger('languageChanged', [lang]);
    
    console.log('语言已切换到: ' + lang);
} 